"""Generate every numeric LaTeX table of the paper from the repository's result files.

Output: report/ieee/tables/tab_*.tex  (booktabs bodies; the wrapping table environment
and caption live in the section files).  Each output carries a header comment naming
its sources.  Run from anywhere:  python report/ieee/tables/make_tables.py
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
import pandas as pd

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "figures"))
from common import (BASE_LABEL, COND_LABEL, COND_ORDER, EVIDENCE, RESULTS, load_aggregate,  # noqa: E402
                    load_json, load_runs, load_stats, load_summary, load_test_cells, parse_test_tables)


def write(name: str, body: str, sources: list[str]) -> None:
    head = "% AUTO-GENERATED by report/ieee/tables/make_tables.py -- do not edit by hand.\n"
    head += "".join(f"% source: {s}\n" for s in sources)
    # The body ends with \bottomrule so that no table row ends exactly at the end of
    # the \input file (a trailing "\\" at EOF breaks the following \bottomrule).
    (HERE / name).write_text(head + body + "\\bottomrule\n", encoding="utf-8", newline="\n")
    print("wrote", name)


def f4(x) -> str:
    return "--" if x is None or (isinstance(x, float) and np.isnan(x)) else f"{x:.4f}"


def pfmt(p) -> str:
    if p is None or (isinstance(p, float) and np.isnan(p)):
        return "--"
    if p == 0:
        return "$<$1e-5"
    if p < 1e-3:
        return f"{p:.1e}".replace("e-0", "e-")
    return f"{p:.4f}" if p < 1 else "1"


summ = load_summary()
test = load_test_cells()
stats = load_stats()
agg = load_aggregate()
runs = load_runs()
tt = parse_test_tables()


def cellrow(base, cond, n):
    s = summ[(summ.base == base) & (summ.condition == cond) & (summ.train_size == n)].iloc[0]
    t = test[(test.base == base) & (test.condition == cond) & (test.train_size == n)].iloc[0]
    return s, t


# ---------------------------------------------------------------- per-size result tables
def results_table(n: int, name: str) -> None:
    lines = []
    for base in ("xlm15", "xlmr"):
        for cond in COND_ORDER:
            s, t = cellrow(base, cond, n)
            deg = int(s.n_tr_stage_degenerate) if not pd.isna(s.n_tr_stage_degenerate) else 0
            lines.append(f"{BASE_LABEL[base]} & {COND_LABEL[cond]} & {s.escape_rate_count} & "
                         f"{s.conditional_macro_f1:.4f} & [{s.conditional_macro_f1_bootstrap_ci[0]:.3f}, {s.conditional_macro_f1_bootstrap_ci[1]:.3f}] & "
                         f"{s.all_seed_macro_f1:.4f} & {t.test_cond:.4f} & {t.test_all:.4f} & {deg} \\\\")
        if base == "xlm15":
            lines.append("\\midrule")
    body = "\n".join(lines) + "\n"
    write(name, body, ["results/summary.csv", "evidence/supplemental/test_tables_received.md (T1)",
                       "results/runs/*.json"])


results_table(2000, "tab_results_2000.tex")
results_table(500, "tab_results_500.tex")

# ---------------------------------------------------------------- XLM-15 size sensitivity
lines = []
for n in (500, 2000, 10000, 20914):
    for cond in ("baza", "tokenizator", "transplant_mean", "transplant_random_coef"):
        s, t = cellrow("xlm15", cond, n)
        lines.append(f"{n:,} & {COND_LABEL[cond]} & {s.escape_rate_count} & {s.conditional_macro_f1:.4f} & "
                     f"{s.all_seed_macro_f1:.4f} & {t.test_cond:.4f} & {t.test_all:.4f} \\\\")
    if n != 20914:
        lines.append("\\addlinespace[2pt]")
write("tab_size_xlm15.tex", "\n".join(lines) + "\n", ["results/summary.csv", "test_tables_received.md (T1)"])

# ---------------------------------------------------------------- 36-cell appendix table
lines = []
for base in ("xlm15", "xlmr"):
    for n in (500, 2000, 10000, 20914):
        for cond in COND_ORDER:
            sub = summ[(summ.base == base) & (summ.condition == cond) & (summ.train_size == n)]
            if not len(sub):
                continue
            s, t = cellrow(base, cond, n)
            deg = "--" if pd.isna(s.n_tr_stage_degenerate) else str(int(s.n_tr_stage_degenerate))
            lines.append(f"{BASE_LABEL[base]} & {n:,} & {COND_LABEL[cond]} & {s.escape_rate_count} & "
                         f"[{s.escape_rate_wilson_ci[0]:.2f}, {s.escape_rate_wilson_ci[1]:.2f}] & "
                         f"{s.conditional_macro_f1:.4f} & [{s.conditional_macro_f1_bootstrap_ci[0]:.3f}, {s.conditional_macro_f1_bootstrap_ci[1]:.3f}] & "
                         f"{s.all_seed_macro_f1:.4f} & [{s.all_seed_macro_f1_bootstrap_ci[0]:.3f}, {s.all_seed_macro_f1_bootstrap_ci[1]:.3f}] & "
                         f"{t.test_cond:.4f} & [{t.test_cond_lo:.3f}, {t.test_cond_hi:.3f}] & {t.test_all:.4f} & "
                         f"{int(s.n_escaped_then_collapsed)} & {deg} \\\\")
        lines.append("\\addlinespace[2pt]")
    if base == "xlm15":
        lines.append("\\midrule")
write("tab_all_cells.tex", "\n".join(lines) + "\n", ["results/summary.csv", "test_tables_received.md (T1)"])

# ---------------------------------------------------------------- XLM-R Direct-relative contrasts
t2 = tt["T2"]


def t2_row(base, n, contrast):
    r = t2[(t2.Base == base) & (t2.n == str(n)) & (t2.Contrast == contrast)]
    return r.iloc[0] if len(r) else None


lines = []
for n in (500, 2000):
    for cond in COND_ORDER[1:]:
        r = stats[(stats.base == "xlmr") & (stats.train_size == n) & (stats.baseline == "baza") & (stats.comparison == cond)].iloc[0]
        tr = t2_row("xlmr", n, f"baza → {cond}")
        dtest = float(tr["Δ test (paired)"]) if tr is not None else float("nan")
        surv = "\\checkmark" if r.survives_family_correction else ""
        lines.append(f"{n:,} & Direct $\\to$ {COND_LABEL[cond]} & {r.conditional_diff:+.4f} & "
                     f"[{r.conditional_ci_low:+.3f}, {r.conditional_ci_high:+.3f}] & {pfmt(r.conditional_p_value)} & "
                     f"{pfmt(r.p_adjusted_holm)} & {pfmt(r.paired_p_value)} & {r.conditional_cohens_d:+.2f} & {dtest:+.4f} & {surv} \\\\")
    if n == 500:
        lines.append("\\midrule")
write("tab_contrasts_xlmr.tex", "\n".join(lines) + "\n", ["results/stats.csv", "test_tables_received.md (T2)"])

# ---------------------------------------------------------------- Turkish contrasts, both bases
def contrast(base, n, b, c):
    """stats.csv row for the contrast b -> c, sign-flipped when stored as c -> b."""
    r = stats[(stats.base == base) & (stats.train_size == n) & (stats.baseline == b) & (stats.comparison == c)]
    sign = 1.0
    if not len(r):
        r = stats[(stats.base == base) & (stats.train_size == n) & (stats.baseline == c) & (stats.comparison == b)]
        sign = -1.0
    r = r.iloc[0].copy()
    for col in ("conditional_diff", "all_seed_diff", "paired_mean_diff", "conditional_cohens_d"):
        if not pd.isna(r[col]):
            r[col] = sign * r[col]
    if sign < 0:
        r["baseline_escape"], r["comparison_escape"] = r["comparison_escape"], r["baseline_escape"]
    return r


def paired_test_delta(base, n, b, c):
    """Mean test-F1 difference over seeds escaped in BOTH arms (T2 definition), from run records."""
    A = {r["seed"]: r for r in runs if r["base"] == base and r["train_size"] == n and r["condition"] == b}
    B = {r["seed"]: r for r in runs if r["base"] == base and r["train_size"] == n and r["condition"] == c}
    shared = [s for s in A if A[s]["escaped"] and B[s]["escaped"]]
    if not shared:
        return None, 0
    return float(np.mean([B[s]["test"]["test_macro_f1"] - A[s]["test"]["test_macro_f1"] for s in shared])), len(shared)


lines = []
for base in ("xlmr", "xlm15"):
    for n in (500, 2000):
        for (b, c, label) in (("baza", "turk", "Direct $\\to$ TR"), ("baza", "turk_qarisiq", "Direct $\\to$ Shuf.\\ TR"),
                              ("turk_qarisiq", "turk", "Shuf.\\ TR $\\to$ TR"), ("baza", "her_ikisi", "Direct $\\to$ OMP+TR"),
                              ("tokenizator", "her_ikisi", "OMP $\\to$ OMP+TR"), ("her_ikisi", "turk", "OMP+TR $\\to$ TR")):
            r = contrast(base, n, b, c)
            dt, ns = paired_test_delta(base, n, b, c)
            dtest = "--" if dt is None else f"{dt:+.4f}"
            shared = "--" if pd.isna(r.n_shared_escaped_seeds) else str(int(r.n_shared_escaped_seeds))
            cd = "--" if r.conditional_status != "MEASURED" else f"{r.conditional_diff:+.4f}"
            surv = "\\checkmark" if r.survives_family_correction else ""
            lines.append(f"{BASE_LABEL[base]} & {n:,} & {label} & {r.baseline_escape}, {r.comparison_escape} & {cd} & "
                         f"{pfmt(r.conditional_p_value)} & {pfmt(r.p_adjusted_holm)} & {shared} & {pfmt(r.paired_p_value)} & "
                         f"{r.all_seed_diff:+.4f} & {dtest} & {surv} \\\\")
        lines.append("\\addlinespace[2pt]")
    if base == "xlmr":
        lines.append("\\midrule")
write("tab_turkish.tex", "\n".join(lines) + "\n", ["results/stats.csv", "results/runs/*.json (paired test delta)"])

# ---------------------------------------------------------------- survivors (T5)
t5 = tt["T5"]
lines = []
t5.columns = ["Base", "size", "Contrast", "dval", "dtest", "nseeds", "t", "p", "holm", "conf"]
for _, r in t5.iterrows():
    b, c = r["Contrast"].split(" → ")
    lines.append(f"{int(r['size']):,} & {COND_LABEL[b]} $\\to$ {COND_LABEL[c]} & {float(r['dval']):+.4f} & {float(r['dtest']):+.4f} & "
                 f"{float(r['t']):+.2f} & {float(r['p']):.2e} & {float(r['holm']):.2e} \\\\")
write("tab_survivors.tex", "\n".join(lines) + "\n", ["evidence/supplemental/test_tables_received.md (T5)", "results/stats.csv"])

# ---------------------------------------------------------------- all paired contrasts (T2)
lines = []
for _, r in t2.iterrows():
    b, c = r["Contrast"].split(" → ")
    dv = r["Δ val (paired)"]; dt = r["Δ test (paired)"]
    lines.append(f"{BASE_LABEL[r['Base']]} & {int(r['n']):,} & {COND_LABEL[b]} $\\to$ {COND_LABEL[c]} & "
                 f"{dv if dv == 'n/a' else f'{float(dv):+.4f}'} & {dt if dt == 'n/a' else f'{float(dt):+.4f}'} & {r['n shared']} & "
                 f"{r['Same sign'].replace('—', '--')} & {float(r['Δ val (all-seed)']):+.4f} & {float(r['Δ test (all-seed)']):+.4f} \\\\")
write("tab_paired_all.tex", "\n".join(lines) + "\n", ["evidence/supplemental/test_tables_received.md (T2)"])

# ---------------------------------------------------------------- errors
err = load_json(RESULTS / "errors.json")
lines = []
for c in COND_ORDER:
    e = err["conditions"][c]
    sh = e["shares_pct"]
    lines.append(f"{COND_LABEL[c]} & {e['n_evaluated']:,} & {e['n_errors']:,} & {e['error_rate_pct']:.2f} & "
                 f"{sh['morfoloji']:.1f} & {sh['texniki_lugat']:.1f} & {sh['yalanci_dost']:.1f} & {sh['diger']:.1f} \\\\")
write("tab_errors.tex", "\n".join(lines) + "\n", ["results/errors.json"])

# ---------------------------------------------------------------- intrinsic diagnostics (3 initialisers x 2 bases)
q = load_json(RESULTS / "cross_base_transplant_quality.json")["per_base"]
norm = {b: load_json(RESULTS / f"embedding_norm_report__{b}.json") for b in ("xlm15", "xlmr")}
lines = []
for b in ("xlm15", "xlmr"):
    for tag, lab in (("omp_k64_rescaled", "OMP"), ("mean_k64_rescaled", "Mean"), ("random_coef_k64_rescaled", "Random")):
        c = load_json(RESULTS / f"controls__{b}__{tag}.json")
        cb, ct = c["C1c_bpc_base"], c["C1c_bpc_transplanted"]
        pre = f"{norm[b]['reconstructed_to_anchor_median_ratio']:.4f}" if tag.startswith("omp") else "--"
        lines.append(f"{BASE_LABEL[b]} & {lab} & {cb['top1_n_correct']}/{cb['top1_n_masked']:,} & "
                     f"{ct['top1_n_correct']}/{ct['top1_n_masked']:,} & {cb['bits_per_character']:.4f} & "
                     f"{ct['bits_per_character']:.4f} & {c['C1c_delta_bpc']:+.4f} & {pre} \\\\")
    if b == "xlm15":
        lines.append("\\midrule")
write("tab_intrinsic.tex", "\n".join(lines) + "\n",
      ["results/controls__{base}__{tag}.json (C1c)", "results/embedding_norm_report__{base}.json (pre-rescale norm ratio)"])

# ---------------------------------------------------------------- anchors
an = load_json(RESULTS / "anchors.json")["bases"]
lines = []
for b in ("xlm15", "xlmr"):
    a = an[b]
    m = a["modes"]
    lines.append(f"{BASE_LABEL[b]} & {a['base_scheme']} & {a['base_vocab_size']:,} & {a['naive_string_overlap']:,} & "
                 f"{m['strict']['n_anchors']:,} & {m['surface']['n_anchors']:,} & {m['functional']['n_anchors']:,} & "
                 f"{m['functional']['anchor_share_of_donor_pct']:.2f} & {a['unfamiliar_tokens']:,} \\\\")
write("tab_anchors.tex", "\n".join(lines) + "\n", ["results/anchors.json"])

# ---------------------------------------------------------------- fidelity controls
lines = []
for b in ("xlm15", "xlmr"):
    c = load_json(RESULTS / f"controls__{b}.json")["C1a_identity"]
    e = c["end_to_end"]
    ratios = [load_json(RESULTS / f"transplant__{b}__{t}.json")["norm_report"]["reconstructed_to_anchor_median_ratio"]
              for t in ("omp_k64_rescaled", "mean_k64_rescaled", "random_coef_k64_rescaled")]
    yn = lambda v: "yes" if v else "no"
    lines.append(f"{BASE_LABEL[b]} & {yn(c['matrix_assignment_identical'])} & {c['collisions']} & "
                 f"{yn(e['embeddings_bit_identical_after_round_trip'])} & {e['max_abs_logit_delta']:.1f} & {yn(e['logits_bit_identical'])} & "
                 + " / ".join(f"{r:.3f}" for r in ratios) + " \\\\")
write("tab_fidelity.tex", "\n".join(lines) + "\n", ["results/controls__{base}.json (C1a_identity)", "results/transplant__{base}__*_rescaled.json (norm_report)"])

# ---------------------------------------------------------------- generalisation gap
d = agg.delta_test_minus_validation_matched
lines = [f"All runs & 164 & {d.mean():+.4f} & {d.median():+.4f} & {d.std():.4f} & {d.min():+.4f} & {d.max():+.4f} & {(d<0).sum()} \\\\"]
for b in ("xlm15", "xlmr"):
    s = agg[agg.base == b].delta_test_minus_validation_matched
    lines.append(f"{BASE_LABEL[b]} & {len(s)} & {s.mean():+.4f} & {s.median():+.4f} & {s.std():.4f} & {s.min():+.4f} & {s.max():+.4f} & {(s<0).sum()} \\\\")
for flag, lab in ((True, "Escaped runs"), (False, "Collapsed runs")):
    s = agg[agg.escaped == flag].delta_test_minus_validation_matched
    lines.append(f"{lab} & {len(s)} & {s.mean():+.4f} & {s.median():+.4f} & {s.std():.4f} & {s.min():+.4f} & {s.max():+.4f} & {(s<0).sum()} \\\\")
write("tab_gap.tex", "\n".join(lines) + "\n", ["results/aggregate.csv"])

# ---------------------------------------------------------------- compute per stage
ls = load_json(RESULTS / "launcher_state.json")
tot_h = agg.runtime_sec.sum() / 3600
az_h = sum(r["az_stage_runtime_sec"] for r in runs) / 3600
lines = []
for b in ("xlm15", "xlmr"):
    s = agg[agg.base == b]
    lines.append(f"{BASE_LABEL[b]} & {len(s)} & {s.runtime_sec.sum()/3600:.2f} & {s.runtime_sec.mean()/60:.2f} & "
                 f"{s.runtime_sec.min()/60:.2f} & {s.runtime_sec.max()/60:.2f} \\\\")
lines.append(f"\\midrule\nAll & 164 & {tot_h:.2f} & {agg.runtime_sec.mean()/60:.2f} & {agg.runtime_sec.min()/60:.2f} & {agg.runtime_sec.max()/60:.2f} \\\\")
write("tab_runtime.tex", "\n".join(lines) + "\n", ["results/aggregate.csv", "results/launcher_state.json"])
print(f"process-hours total {tot_h:.2f}, AZ stage {az_h:.2f}, launcher elapsed {ls['elapsed_sec']/3600:.2f} h")

# ---------------------------------------------------------------- tokenizer diagnostics
ov = load_json(RESULTS / "overlap_control.json")["models"]
dia = load_json(EVIDENCE / "carried_forward_pre_grid" / "diacritics.json")["vocab_letter_counts"]
trunc = load_json(RESULTS / "truncation.json")
_an = load_json(RESULTS / "anchors.json")["bases"]
vocab_size = {"xlm15": _an["xlm15"]["base_vocab_size"], "xlmr": _an["xlmr"]["base_vocab_size"],
              "donor": _an["xlmr"]["donor_vocab_size"]}  # grid-time sizes (diacritics.json predates them)
key = {"FacebookAI/xlm-mlm-tlm-xnli15-1024": ("xlm15", "base_original_xlm15"),
       "xlm-roberta-base": ("xlmr", "contrast_original_xlmr"),
       "HPLT/hplt_bert_base_az": ("donor", "donor_transplanted")}
name = {"xlm15": "XLM-15", "xlmr": "XLM-R", "donor": "AZ donor"}
lines = []
for m in ov:
    k, tk = key[m["model"]]
    rs = m["relatedness_signal"]
    letters = dia[k]
    ld = trunc["length_distribution"][tk]
    t128 = trunc["by_max_length"]["128"]["setups"][tk]["truncation_rate_pct"]
    t256 = trunc["by_max_length"]["256"]["setups"][tk]["truncation_rate_pct"]
    lines.append(f"{name[k]} & {vocab_size[k]:,} & {m['az_fertility']:.3f} & {m['az_types_alpha']:,} & "
                 f"{m['overlaps']['tr']['alpha']['a_covered_pct']:.1f} & {m['overlaps']['en']['alpha']['a_covered_pct']:.1f} & "
                 f"{m['overlaps']['fi']['alpha']['a_covered_pct']:.1f} & {m['overlaps']['ru']['alpha']['a_covered_pct']:.1f} & "
                 f"{rs['relatedness_lift_points']:+.1f} & {letters['ə']:,} & {letters['ş']:,} & {letters['ğ']:,} & "
                 f"{ld['tokens_mean']:.1f} & {ld['tokens_p99']:.0f} & {t128:.2f} & {t256:.2f} \\\\")
write("tab_tokenizer.tex", "\n".join(lines) + "\n",
      ["results/overlap_control.json", "results/truncation.json",
       "evidence/carried_forward_pre_grid/diacritics.json (pre-grid vocabulary letter counts)"])

# ---------------------------------------------------------------- probe words
fert = load_json(RESULTS / "fertility.json")["models"]
words = list(fert[0]["probe_words"].keys())
lines = []
for w in words:
    cells = []
    for m in fert:
        pw = m["probe_words"][w]
        pieces = " ".join(p.replace("▁", "\\textvisiblespace{}").replace("</w>", "$\\cdot$") for p in pw["pieces"])
        cells.append(f"\\texttt{{{pieces}}} ({pw['n_pieces']})")
    lines.append(f"\\textit{{{w}}} & " + " & ".join(cells) + " \\\\")
write("tab_probes.tex", "\n".join(lines) + "\n", ["results/fertility.json"])

# ---------------------------------------------------------------- multiplicity summary numbers
meas = int((stats.conditional_status == "MEASURED").sum())
surv = int(stats.survives_family_correction.sum())
print(f"declared {len(stats)} measurable {meas} survivors {surv} bonferroni {0.05/meas:.2e}")
